version: 1.4.9.8a{build}
max_jobs: 15
image: Visual Studio 2017
configuration: Release
platform: x86
#environment:
#  SECRET_KEY:
#    secure: Aj3VN2tlLSPP6QhY5bTXIUJiI/de9iTyr3wpO3FPDSLkXj/Il1nV+I+PCrl7ci94Rqv6KtVXIxzfvk0yXjN7u9CVYU3y1oMIzp3cM6u2fVOdaIX06RTNlF2EunvxLZoG/etETEUfb7O8kBIPxEmSd5E+/1cp0igjKsiTlqq5ivA=
#install:
#- nuget install secure-file -ExcludeVersion
#- secure-file\tools\secure-file -decrypt ./Tools/private_encryption.py.enc -secret %SECRET_KEY% -out ./Tools/private_encryption.py
#- secure-file\tools\secure-file -decrypt ./PC/encryption_private.h.enc -secret %SECRET_KEY% -out ./PC/encryption_private.h
before_build:
- cmd: call ci_build.bat
#cache:
#- .\externals\cpython
#- .\externals\aes
#- .\obj
#- .\bin
build:
  project: PCbuild\PCbuild.sln
  parallel: true
  verbosity: minimal
test: off
